"""Added battle tag

Revision ID: 49057497ee22
Revises: dfc8ebfbd496
Create Date: 2023-04-19 19:57:16.447862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49057497ee22'
down_revision = 'dfc8ebfbd496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mt_g_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('battle', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mt_g_cards', schema=None) as batch_op:
        batch_op.drop_column('battle')

    # ### end Alembic commands ###
