"""Added collector number

Revision ID: 790052065a45
Revises: 
Create Date: 2023-04-06 18:51:47.069993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790052065a45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mt_g_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collector_number', sa.String(length=50), nullable=True))

    with op.batch_alter_table('mt_g_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collector_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mt_g_decks', schema=None) as batch_op:
        batch_op.drop_column('collector_number')

    with op.batch_alter_table('mt_g_cards', schema=None) as batch_op:
        batch_op.drop_column('collector_number')

    # ### end Alembic commands ###
