"""Added back face info

Revision ID: dfc8ebfbd496
Revises: 790052065a45
Create Date: 2023-04-19 16:51:14.380837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc8ebfbd496'
down_revision = '790052065a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mt_g_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('back_small_img', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('back_normal_img', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('back_large_img', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('back_png_img', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('back_border_img', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mt_g_cards', schema=None) as batch_op:
        batch_op.drop_column('back_border_img')
        batch_op.drop_column('back_png_img')
        batch_op.drop_column('back_large_img')
        batch_op.drop_column('back_normal_img')
        batch_op.drop_column('back_small_img')

    # ### end Alembic commands ###
